<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Attachment;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * Tax-invoice email with the rendered invoice PDF attached. The PDF bytes are
 * generated by InvoiceMailController (dompdf) and passed in.
 */
class InvoiceMail extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(public array $data, public string $pdf) {}

    public function envelope(): Envelope
    {
        return new Envelope(subject: 'Tax Invoice ' . ($this->data['invoiceNo'] ?? ''));
    }

    public function content(): Content
    {
        return new Content(view: 'emails.invoice', with: ['d' => $this->data]);
    }

    public function attachments(): array
    {
        return [
            Attachment::fromData(fn () => $this->pdf, ($this->data['invoiceNo'] ?? 'invoice') . '.pdf')
                ->withMime('application/pdf'),
        ];
    }
}
