<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventoryPurchaseSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('inventory_purchases')->count() > 0) {
            return;
        }

        $now = now();

        $rows = [
            [
                'date' => '2026-05-24',
                'billNo' => 'VEG-24-557',
                'billDate' => '2026-05-24',
                'vendor' => 'Crawford Market Vendor — Suresh',
                'vendorGstin' => '',
                'vendorPan' => '',
                'vendorPhone' => '+91 98201 23456',
                'category' => 'Vegetables',
                'department' => 'Kitchen',
                'discount' => 0,
                'freight' => 0,
                'roundOff' => 0,
                'interState' => false,
                'paymentStatus' => 'Paid',
                'paymentMode' => 'Cash',
                'paymentDate' => '2026-05-24',
                'paymentRef' => 'RCP-1142',
                'paidAmount' => 2660,
                'receivedBy' => 'Chef Joseph D.',
                'qcStatus' => 'Accepted',
                'storage' => 'Cold Storage',
                'notes' => 'Daily morning purchase · all fresh stock',
                'lines' => json_encode([
                    [
                        'id' => 'l1',
                        'item' => 'Onion (red)',
                        'unit' => 'kg',
                        'qty' => 25,
                        'rate' => 32,
                        'gstPct' => 0,
                        'taxable' => 800,
                        'tax' => 0,
                        'amount' => 800,
                    ],
                    [
                        'id' => 'l2',
                        'item' => 'Tomato',
                        'unit' => 'kg',
                        'qty' => 15,
                        'rate' => 28,
                        'gstPct' => 0,
                        'taxable' => 420,
                        'tax' => 0,
                        'amount' => 420,
                    ],
                    [
                        'id' => 'l3',
                        'item' => 'Potato',
                        'unit' => 'kg',
                        'qty' => 30,
                        'rate' => 22,
                        'gstPct' => 0,
                        'taxable' => 660,
                        'tax' => 0,
                        'amount' => 660,
                    ],
                    [
                        'id' => 'l4',
                        'item' => 'Coriander',
                        'unit' => 'bunch',
                        'qty' => 20,
                        'rate' => 12,
                        'gstPct' => 0,
                        'taxable' => 240,
                        'tax' => 0,
                        'amount' => 240,
                    ],
                    [
                        'id' => 'l5',
                        'item' => 'Green chilli',
                        'unit' => 'kg',
                        'qty' => 3,
                        'rate' => 80,
                        'gstPct' => 0,
                        'taxable' => 240,
                        'tax' => 0,
                        'amount' => 240,
                    ],
                    [
                        'id' => 'l6',
                        'item' => 'Lemon',
                        'unit' => 'kg',
                        'qty' => 5,
                        'rate' => 60,
                        'gstPct' => 0,
                        'taxable' => 300,
                        'tax' => 0,
                        'amount' => 300,
                    ],
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'date' => '2026-05-24',
                'billNo' => 'NV-25-441',
                'billDate' => '2026-05-24',
                'vendor' => 'Al-Mansoor Chicken Supply',
                'vendorGstin' => '27ABFCM1234A1Z3',
                'vendorPan' => 'ABFCM1234A',
                'vendorPhone' => '+91 99876 12345',
                'category' => 'Non-veg (Meat / Fish)',
                'department' => 'Kitchen',
                'discount' => 0,
                'freight' => 0,
                'roundOff' => 0,
                'interState' => false,
                'paymentStatus' => 'Paid',
                'paymentMode' => 'UPI',
                'paymentDate' => '2026-05-24',
                'paymentRef' => '240524AB7741',
                'paidAmount' => 17690,
                'receivedBy' => 'Chef Joseph D.',
                'qcStatus' => 'Accepted',
                'storage' => 'Freezer',
                'notes' => 'Temperature checked at receipt · 4°C ✓ · 30-day frozen stock',
                'lines' => json_encode([
                    [
                        'id' => 'l1',
                        'item' => 'Chicken Boneless (1.2kg/pc)',
                        'unit' => 'kg',
                        'qty' => 24,
                        'rate' => 320,
                        'gstPct' => 0,
                        'taxable' => 7680,
                        'tax' => 0,
                        'amount' => 7680,
                    ],
                    [
                        'id' => 'l2',
                        'item' => 'Mutton (curry cut)',
                        'unit' => 'kg',
                        'qty' => 8,
                        'rate' => 720,
                        'gstPct' => 0,
                        'taxable' => 5760,
                        'tax' => 0,
                        'amount' => 5760,
                    ],
                    [
                        'id' => 'l3',
                        'item' => 'Pomfret (medium)',
                        'unit' => 'kg',
                        'qty' => 5,
                        'rate' => 850,
                        'gstPct' => 0,
                        'taxable' => 4250,
                        'tax' => 0,
                        'amount' => 4250,
                    ],
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'date' => '2026-05-23',
                'billNo' => 'DAI-23-2188',
                'billDate' => '2026-05-23',
                'vendor' => 'Amul Dairy Distributor',
                'vendorGstin' => '27AAACG1234B1Z9',
                'vendorPan' => 'AAACG1234B',
                'vendorPhone' => '+91 22 6669 8800',
                'category' => 'Dairy & Eggs',
                'department' => 'Kitchen',
                'discount' => 100,
                'freight' => 0,
                'roundOff' => -4,
                'interState' => false,
                'paymentStatus' => 'On Credit',
                'paymentMode' => 'Credit (30 days)',
                'paidAmount' => 0,
                'receivedBy' => 'Chef Joseph D.',
                'qcStatus' => 'Accepted',
                'storage' => 'Cold Storage',
                'notes' => 'Credit period 30 days · vendor approved',
                'lines' => json_encode([
                    [
                        'id' => 'l1',
                        'item' => 'Milk (toned, 1L)',
                        'unit' => 'litre',
                        'qty' => 80,
                        'rate' => 64,
                        'gstPct' => 0,
                        'taxable' => 5120,
                        'tax' => 0,
                        'amount' => 5120,
                    ],
                    [
                        'id' => 'l2',
                        'item' => 'Curd (5kg tub)',
                        'unit' => 'tin',
                        'qty' => 8,
                        'rate' => 380,
                        'gstPct' => 0,
                        'taxable' => 3040,
                        'tax' => 0,
                        'amount' => 3040,
                    ],
                    [
                        'id' => 'l3',
                        'item' => 'Paneer (fresh)',
                        'unit' => 'kg',
                        'qty' => 6,
                        'rate' => 380,
                        'gstPct' => 5,
                        'taxable' => 2280,
                        'tax' => 114,
                        'amount' => 2394,
                    ],
                    [
                        'id' => 'l4',
                        'item' => 'Egg (tray of 30)',
                        'unit' => 'tray',
                        'qty' => 10,
                        'rate' => 240,
                        'gstPct' => 0,
                        'taxable' => 2400,
                        'tax' => 0,
                        'amount' => 2400,
                    ],
                    [
                        'id' => 'l5',
                        'item' => 'Amul butter (500g)',
                        'unit' => 'pcs',
                        'qty' => 12,
                        'rate' => 285,
                        'gstPct' => 12,
                        'taxable' => 3420,
                        'tax' => 410,
                        'amount' => 3830,
                    ],
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'date' => '2026-05-22',
                'billNo' => 'GRO-MAY-2241',
                'billDate' => '2026-05-22',
                'vendor' => 'ABC Wholesale Grains',
                'vendorGstin' => '27AABCA1234C1Z5',
                'vendorPan' => 'AABCA1234C',
                'vendorPhone' => '+91 22 6789 1100',
                'category' => 'Dry Groceries',
                'department' => 'Kitchen',
                'discount' => 250,
                'freight' => 200,
                'roundOff' => 0,
                'interState' => false,
                'paymentStatus' => 'Paid',
                'paymentMode' => 'NEFT',
                'paymentDate' => '2026-05-22',
                'paymentRef' => 'HDFCN52522001',
                'paidAmount' => 40790,
                'receivedBy' => 'Store · Sunil V.',
                'qcStatus' => 'Accepted',
                'storage' => 'Dry Store',
                'notes' => 'Monthly bulk · GRN # GRN-2026-051 attached',
                'lines' => json_encode([
                    [
                        'id' => 'l1',
                        'item' => 'Basmati Rice (10kg bag)',
                        'unit' => 'bag',
                        'qty' => 12,
                        'rate' => 1850,
                        'gstPct' => 5,
                        'taxable' => 22200,
                        'tax' => 1110,
                        'amount' => 23310,
                    ],
                    [
                        'id' => 'l2',
                        'item' => 'Toor Dal',
                        'unit' => 'kg',
                        'qty' => 20,
                        'rate' => 180,
                        'gstPct' => 0,
                        'taxable' => 3600,
                        'tax' => 0,
                        'amount' => 3600,
                    ],
                    [
                        'id' => 'l3',
                        'item' => 'Wheat Atta (10kg bag)',
                        'unit' => 'bag',
                        'qty' => 8,
                        'rate' => 480,
                        'gstPct' => 0,
                        'taxable' => 3840,
                        'tax' => 0,
                        'amount' => 3840,
                    ],
                    [
                        'id' => 'l4',
                        'item' => 'Sugar',
                        'unit' => 'kg',
                        'qty' => 50,
                        'rate' => 48,
                        'gstPct' => 5,
                        'taxable' => 2400,
                        'tax' => 120,
                        'amount' => 2520,
                    ],
                    [
                        'id' => 'l5',
                        'item' => 'Refined Oil (15L tin)',
                        'unit' => 'tin',
                        'qty' => 4,
                        'rate' => 1850,
                        'gstPct' => 5,
                        'taxable' => 7400,
                        'tax' => 370,
                        'amount' => 7770,
                    ],
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'date' => '2026-05-20',
                'billNo' => 'ABC-2426',
                'billDate' => '2026-05-20',
                'vendor' => 'ABC Linens Pvt',
                'vendorGstin' => '27ABCDE1234F1Z5',
                'vendorPan' => 'ABCDE1234F',
                'vendorPhone' => '+91 22 4567 8900',
                'category' => 'Linen',
                'department' => 'Housekeeping',
                'discount' => 1500,
                'freight' => 350,
                'roundOff' => -2,
                'interState' => false,
                'paymentStatus' => 'Partial',
                'paymentMode' => 'Cheque',
                'paymentDate' => '2026-05-20',
                'paymentRef' => '412580',
                'paidAmount' => 50000,
                'receivedBy' => 'HK Manager · Maria L.',
                'qcStatus' => 'Accepted',
                'storage' => 'Linen Store',
                'notes' => 'Cheque ₹50,000 advance · balance Net 30',
                'lines' => json_encode([
                    [
                        'id' => 'l1',
                        'item' => 'Bath Towel — Large (600gsm)',
                        'unit' => 'pcs',
                        'qty' => 60,
                        'rate' => 580,
                        'gstPct' => 18,
                        'taxable' => 34800,
                        'tax' => 6264,
                        'amount' => 41064,
                    ],
                    [
                        'id' => 'l2',
                        'item' => 'Bed Sheet — King (300TC)',
                        'unit' => 'pcs',
                        'qty' => 24,
                        'rate' => 850,
                        'gstPct' => 18,
                        'taxable' => 20400,
                        'tax' => 3672,
                        'amount' => 24072,
                    ],
                    [
                        'id' => 'l3',
                        'item' => 'Pillow Cover Standard',
                        'unit' => 'pcs',
                        'qty' => 96,
                        'rate' => 180,
                        'gstPct' => 18,
                        'taxable' => 17280,
                        'tax' => 3110,
                        'amount' => 20390,
                    ],
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'date' => '2026-05-18',
                'billNo' => 'TC-1101',
                'billDate' => '2026-05-18',
                'vendor' => 'TechCorp IT Services',
                'vendorGstin' => '27TECHC1234E1Z1',
                'vendorPan' => 'TECHC1234E',
                'vendorPhone' => '+91 80 2233 4455',
                'category' => 'IT Equipment',
                'department' => 'IT',
                'discount' => 0,
                'freight' => 0,
                'roundOff' => 0,
                'interState' => false,
                'paymentStatus' => 'Unpaid',
                'paymentMode' => 'Pending',
                'paidAmount' => 0,
                'receivedBy' => 'IT · Aman S.',
                'qcStatus' => 'Accepted',
                'storage' => 'Maintenance Store',
                'notes' => 'Net 30 · invoice goes to accounts',
                'lines' => json_encode([
                    [
                        'id' => 'l1',
                        'item' => 'Wireless Access Point (Cisco)',
                        'unit' => 'pcs',
                        'qty' => 6,
                        'rate' => 18500,
                        'gstPct' => 18,
                        'taxable' => 111000,
                        'tax' => 19980,
                        'amount' => 130980,
                    ],
                    [
                        'id' => 'l2',
                        'item' => 'Network switch 24-port',
                        'unit' => 'pcs',
                        'qty' => 2,
                        'rate' => 9500,
                        'gstPct' => 18,
                        'taxable' => 19000,
                        'tax' => 3420,
                        'amount' => 22420,
                    ],
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'date' => '2026-05-15',
                'billNo' => 'OFC-15-901',
                'billDate' => '2026-05-15',
                'vendor' => 'Pearl Office Solutions',
                'vendorGstin' => '27PEARL1234O1Z2',
                'vendorPan' => 'PEARL1234O',
                'vendorPhone' => '+91 22 4444 1212',
                'category' => 'Office Equipment',
                'department' => 'Front Office',
                'discount' => 500,
                'freight' => 0,
                'roundOff' => 0,
                'interState' => false,
                'paymentStatus' => 'Paid',
                'paymentMode' => 'NEFT',
                'paymentDate' => '2026-05-16',
                'paymentRef' => 'HDFCN51616044',
                'paidAmount' => 83964,
                'receivedBy' => 'Admin · Reena T.',
                'qcStatus' => 'Accepted',
                'storage' => 'Office',
                'notes' => 'Annual office refresh · approved by Owner',
                'lines' => json_encode([
                    [
                        'id' => 'l1',
                        'item' => 'Front-office computer monitor (24")',
                        'unit' => 'pcs',
                        'qty' => 3,
                        'rate' => 12500,
                        'gstPct' => 18,
                        'taxable' => 37500,
                        'tax' => 6750,
                        'amount' => 44250,
                    ],
                    [
                        'id' => 'l2',
                        'item' => 'Office chair (mesh ergo)',
                        'unit' => 'pcs',
                        'qty' => 4,
                        'rate' => 7800,
                        'gstPct' => 18,
                        'taxable' => 31200,
                        'tax' => 5616,
                        'amount' => 36816,
                    ],
                    [
                        'id' => 'l3',
                        'item' => 'Stapler heavy-duty + clips',
                        'unit' => 'set',
                        'qty' => 6,
                        'rate' => 480,
                        'gstPct' => 18,
                        'taxable' => 2880,
                        'tax' => 518,
                        'amount' => 3398,
                    ],
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Insert row-by-row: rows have varying optional keys (paymentDate/Ref),
        // which a single batch insert can't handle.
        foreach ($rows as $r) {
            DB::table('inventory_purchases')->insert($r);
        }
    }
}
