<?php

namespace Database\Seeders;

use App\Models\RoomAmenity;
use Illuminate\Database\Seeder;

class RoomAmenitySeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['name' => 'King Bed Sheet (300TC cotton)', 'category' => 'Bedding', 'qty' => 240, 'unit' => 'pcs', 'purchaseDate' => '2025-11-08', 'purchasePrice' => 850, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🛏️', 'remark' => '3 sets per room rotation', 'perRoom' => 3],
            ['name' => 'Queen Bed Sheet (300TC cotton)', 'category' => 'Bedding', 'qty' => 180, 'unit' => 'pcs', 'purchaseDate' => '2025-11-08', 'purchasePrice' => 720, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🛏️', 'remark' => 'Twin room sets', 'perRoom' => 3],
            ['name' => 'Pillow — Memory Foam', 'category' => 'Bedding', 'qty' => 192, 'unit' => 'pcs', 'purchaseDate' => '2025-09-22', 'purchasePrice' => 1450, 'vendor' => 'Sleepwell', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🛏️', 'remark' => '2 per room + 1 spare', 'perRoom' => 2],
            ['name' => 'Pillow — Down Soft', 'category' => 'Bedding', 'qty' => 96, 'unit' => 'pcs', 'purchaseDate' => '2025-09-22', 'purchasePrice' => 1850, 'vendor' => 'Sleepwell', 'condition' => 'Good', 'location' => 'Suite', 'photo' => '🛌', 'remark' => 'Suites + VIP rooms', 'perRoom' => 2],
            ['name' => 'Duvet — King (microfiber)', 'category' => 'Bedding', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-08-14', 'purchasePrice' => 3200, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🛏️', 'remark' => 'Winter weight', 'perRoom' => 1],
            ['name' => 'Duvet Cover — King', 'category' => 'Bedding', 'qty' => 168, 'unit' => 'pcs', 'purchaseDate' => '2025-08-14', 'purchasePrice' => 1100, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🛏️', 'remark' => '2 per duvet for rotation', 'perRoom' => 2],
            ['name' => 'Pillow Cover — Standard', 'category' => 'Bedding', 'qty' => 576, 'unit' => 'pcs', 'purchaseDate' => '2025-09-22', 'purchasePrice' => 180, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🛏️', 'remark' => '3 per pillow rotation', 'perRoom' => 6],
            ['name' => 'Mattress Protector (waterproof)', 'category' => 'Bedding', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-07-30', 'purchasePrice' => 1600, 'vendor' => 'Sleepwell', 'condition' => 'New', 'location' => 'All Rooms', 'photo' => '🛏️', 'remark' => 'Bed-bug + spill protection', 'perRoom' => 1],
            ['name' => 'Bed Runner (decorative)', 'category' => 'Bedding', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-10-12', 'purchasePrice' => 950, 'vendor' => 'Royal Furnishings', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🛏️', 'remark' => 'Foot of bed accent', 'perRoom' => 1],
            ['name' => 'Bath Towel — Large (600gsm)', 'category' => 'Bath', 'qty' => 240, 'unit' => 'pcs', 'purchaseDate' => '2025-12-05', 'purchasePrice' => 580, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🧖', 'remark' => 'Hand of guests · 3 per room', 'perRoom' => 3],
            ['name' => 'Hand Towel', 'category' => 'Bath', 'qty' => 240, 'unit' => 'pcs', 'purchaseDate' => '2025-12-05', 'purchasePrice' => 220, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🤲', 'remark' => 'Vanity tray', 'perRoom' => 3],
            ['name' => 'Face Towel', 'category' => 'Bath', 'qty' => 240, 'unit' => 'pcs', 'purchaseDate' => '2025-12-05', 'purchasePrice' => 120, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🤲', 'remark' => '', 'perRoom' => 3],
            ['name' => 'Bath Mat (cotton)', 'category' => 'Bath', 'qty' => 96, 'unit' => 'pcs', 'purchaseDate' => '2025-12-05', 'purchasePrice' => 380, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🛁', 'remark' => '1 per bathroom', 'perRoom' => 1],
            ['name' => 'Bathrobe — Waffle', 'category' => 'Bath', 'qty' => 60, 'unit' => 'pcs', 'purchaseDate' => '2025-12-05', 'purchasePrice' => 1850, 'vendor' => 'Pearl Textiles', 'condition' => 'Good', 'location' => 'Suite', 'photo' => '🥋', 'remark' => 'Suite & deluxe only', 'perRoom' => 2],
            ['name' => 'Slippers — Disposable', 'category' => 'Bath', 'qty' => 480, 'unit' => 'pair', 'purchaseDate' => '2026-01-15', 'purchasePrice' => 80, 'vendor' => 'Luxor Amenities', 'condition' => 'New', 'location' => 'Linen Store', 'photo' => '🥿', 'remark' => 'Replenish after each checkout', 'perRoom' => 2],
            ['name' => 'Shower Cap', 'category' => 'Bath', 'qty' => 480, 'unit' => 'pcs', 'purchaseDate' => '2026-01-15', 'purchasePrice' => 12, 'vendor' => 'Luxor Amenities', 'condition' => 'New', 'location' => 'Linen Store', 'photo' => '🛁', 'remark' => 'Bathroom counter', 'perRoom' => 2],
            ['name' => 'Bedside Lamp (LED, USB)', 'category' => 'Furniture', 'qty' => 168, 'unit' => 'pcs', 'purchaseDate' => '2025-06-18', 'purchasePrice' => 1850, 'vendor' => 'Bajaj Lighting', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '💡', 'remark' => 'Touch dim, USB-C charging', 'perRoom' => 2],
            ['name' => 'Desk Chair (ergonomic)', 'category' => 'Furniture', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-04-20', 'purchasePrice' => 7800, 'vendor' => 'Featherlite', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🪑', 'remark' => 'Replace 4 with caster issue', 'perRoom' => 1],
            ['name' => 'Luggage Rack (folding)', 'category' => 'Furniture', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-05-08', 'purchasePrice' => 2400, 'vendor' => 'Royal Furnishings', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🧳', 'remark' => 'Beech wood', 'perRoom' => 1],
            ['name' => 'In-room Safe (digital)', 'category' => 'Furniture', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2024-11-10', 'purchasePrice' => 8500, 'vendor' => 'Godrej Safe', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🔒', 'remark' => 'Master override key in mgr office', 'perRoom' => 1],
            ['name' => 'Television — 43" Smart LED', 'category' => 'Electronics', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-02-14', 'purchasePrice' => 32500, 'vendor' => 'LG Electronics', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '📺', 'remark' => 'Built-in Chromecast', 'perRoom' => 1],
            ['name' => 'Television — 55" (Suite)', 'category' => 'Electronics', 'qty' => 12, 'unit' => 'pcs', 'purchaseDate' => '2025-02-14', 'purchasePrice' => 52500, 'vendor' => 'LG Electronics', 'condition' => 'Good', 'location' => 'Suite', 'photo' => '📺', 'remark' => '4K · suites only', 'perRoom' => 1],
            ['name' => 'Hair Dryer — Wall mount 1800W', 'category' => 'Electronics', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-05-22', 'purchasePrice' => 2200, 'vendor' => 'Bajaj Electricals', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '💨', 'remark' => 'Mounted in bathroom', 'perRoom' => 1],
            ['name' => 'Electric Kettle — 1L', 'category' => 'Electronics', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2026-01-22', 'purchasePrice' => 1450, 'vendor' => 'Bajaj Electricals', 'condition' => 'New', 'location' => 'All Rooms', 'photo' => '🫖', 'remark' => 'Tea/coffee station', 'perRoom' => 1],
            ['name' => 'Iron + Board (folding)', 'category' => 'Electronics', 'qty' => 84, 'unit' => 'set', 'purchaseDate' => '2025-08-30', 'purchasePrice' => 2850, 'vendor' => 'Bajaj Electricals', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '👔', 'remark' => 'Steam iron + folding board', 'perRoom' => 1],
            ['name' => 'Phone — IP Desk Phone', 'category' => 'Electronics', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2024-09-12', 'purchasePrice' => 4200, 'vendor' => 'Cisco', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '📞', 'remark' => 'VoIP · ext + concierge dial-0', 'perRoom' => 1],
            ['name' => 'Alarm Clock with USB charger', 'category' => 'Electronics', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-10-05', 'purchasePrice' => 1100, 'vendor' => 'Bajaj Electricals', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '⏰', 'remark' => 'Bedside · USB-A + USB-C', 'perRoom' => 1],
            ['name' => 'Soap Dispenser (wall)', 'category' => 'Toiletries', 'qty' => 168, 'unit' => 'pcs', 'purchaseDate' => '2025-07-15', 'purchasePrice' => 480, 'vendor' => 'Luxor Amenities', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🧼', 'remark' => '2 per bathroom (basin + shower)', 'perRoom' => 2],
            ['name' => 'Tissue Box Cover (ceramic)', 'category' => 'Toiletries', 'qty' => 96, 'unit' => 'pcs', 'purchaseDate' => '2025-09-10', 'purchasePrice' => 380, 'vendor' => 'Royal Furnishings', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🧻', 'remark' => 'Replace damaged 6', 'perRoom' => 1],
            ['name' => 'Blackout Curtain — Double layer', 'category' => 'Decor', 'qty' => 168, 'unit' => 'pcs', 'purchaseDate' => '2024-12-20', 'purchasePrice' => 4200, 'vendor' => 'Royal Furnishings', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🪟', 'remark' => '2 per window x 1 window/room', 'perRoom' => 2],
            ['name' => 'Sheer Curtain (linen)', 'category' => 'Decor', 'qty' => 168, 'unit' => 'pcs', 'purchaseDate' => '2024-12-20', 'purchasePrice' => 1800, 'vendor' => 'Royal Furnishings', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🪟', 'remark' => 'Under blackout layer', 'perRoom' => 2],
            ['name' => 'Bedside Rug (3×5 ft)', 'category' => 'Decor', 'qty' => 168, 'unit' => 'pcs', 'purchaseDate' => '2025-01-25', 'purchasePrice' => 2400, 'vendor' => 'Carpet Co. Mumbai', 'condition' => 'Fair', 'location' => 'All Rooms', 'photo' => '🟫', 'remark' => '12 showing wear · plan replacement', 'perRoom' => 2],
            ['name' => 'Wall Art (framed prints)', 'category' => 'Decor', 'qty' => 168, 'unit' => 'pcs', 'purchaseDate' => '2024-08-30', 'purchasePrice' => 1850, 'vendor' => 'Mumbai Frames', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🖼️', 'remark' => 'Curated set · 2 per room', 'perRoom' => 2],
            ['name' => 'Minibar Fridge (40L)', 'category' => 'Minibar', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2024-10-12', 'purchasePrice' => 9800, 'vendor' => 'Godrej', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '🧊', 'remark' => 'Inside cabinetry', 'perRoom' => 1],
            ['name' => 'Coffee/Tea Tray (welcome set)', 'category' => 'Minibar', 'qty' => 84, 'unit' => 'set', 'purchaseDate' => '2025-06-08', 'purchasePrice' => 1450, 'vendor' => 'Royal Crockery', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '☕', 'remark' => 'Tray + jars + spoons + napkin', 'perRoom' => 1],
            ['name' => 'Stationery Folder (welcome)', 'category' => 'Stationery', 'qty' => 84, 'unit' => 'pcs', 'purchaseDate' => '2025-03-18', 'purchasePrice' => 850, 'vendor' => 'Pearl Press', 'condition' => 'Good', 'location' => 'All Rooms', 'photo' => '📓', 'remark' => 'Letterhead, envelopes, pen, pad', 'perRoom' => 1],
            ['name' => 'Hotel Pen (branded)', 'category' => 'Stationery', 'qty' => 600, 'unit' => 'pcs', 'purchaseDate' => '2025-11-02', 'purchasePrice' => 24, 'vendor' => 'Pearl Press', 'condition' => 'New', 'location' => 'All Rooms', 'photo' => '🖊️', 'remark' => 'Replenish per checkout · take-home', 'perRoom' => 2],
            ['name' => 'Notepad (50 sheets)', 'category' => 'Stationery', 'qty' => 240, 'unit' => 'pcs', 'purchaseDate' => '2025-11-02', 'purchasePrice' => 45, 'vendor' => 'Pearl Press', 'condition' => 'New', 'location' => 'All Rooms', 'photo' => '📝', 'remark' => 'Replenish weekly', 'perRoom' => 1],
        ];
        foreach ($rows as $row) {
            RoomAmenity::firstOrCreate(['name' => $row['name']], $row);
        }
    }
}
